apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploysafe-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: deploysafe-container
          image: deploysafe-portfolio:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000